<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CDC2-L-025418W" name="InterviewQuestions.TimeOutExample" tests="1" failures="0" timestamp="03 Jan 2021 17:53:31 GMT" time="2.025" errors="1">
  <testcase name="testCase" time="2.025" classname="InterviewQuestions.TimeOutExample">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method InterviewQuestions.TimeOutExample.testCase() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method InterviewQuestions.TimeOutExample.testCase() didn't finish within the time-out 2000
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:69)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testCase -->
</testsuite> <!-- InterviewQuestions.TimeOutExample -->
